<!doctype html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title><?php echo $blocktitle ?? 'Welcome'; ?> :: Formation php avancé</title>
</head>
<body>
    <h1><?php echo $blocktitle ?? 'Default title'; ?></h1>
    <hr />

    <?php echo $blockbody; ?>
</body>
</html>