[block:title]
    Soap : Liste des produits
[endblock]

[block:body]

<h3>Liste des produits</h3>

<table width="100%" border="1" cellpadding="5" cellspacing="0">
    <thead>
    <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Price</th>
        <th>Description</th>
        <th>Date</th>
    </tr>
    </thead>
    <?php
    foreach ($products as $product): ?>
    <tr>
        <td><?php echo $product->id; ?></td>
        <td><?php echo $product->name; ?></td>
        <td><?php echo $product->price; ?></td>
        <td><?php echo $product->description; ?></td>
        <td><?php /*echo $product->getDate()->format("d/m/Y");*/ ?></td>
    </tr>
    <?php endforeach; ?>
</table>

[endblock]
