[block:title]
    Design Pattern
[endblock]

[block:body]

<ul>
    <li><a href="<?php echo $this->generateUrl('design_pattern_singleton'); ?>">Singleton</a></li>
    <li><a href="<?php echo $this->generateUrl('design_pattern_collection'); ?>">Collection</a></li>
    <li><a href="<?php echo $this->generateUrl('design_pattern_table'); ?>">TableBuilder</a></li>
    <li><a href="<?php echo $this->generateUrl('design_pattern_query'); ?>">QueryBuilder</a></li>
</ul>

[endblock]