[block:title]
    Liste des produits
[endblock]

[block:body]

<h3>Liste des produits</h3>
<p>
    <a href="<?php echo $this->generateUrl('orm_add'); ?>">Ajouter</a>
</p>
<table width="100%" border="1" cellpadding="5" cellspacing="0">
    <thead>
    <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Price</th>
        <th>Description</th>
        <th>Date</th>
        <th></th>
    </tr>
    </thead>
    <?php /** @var \App\Model\Product $product */
    foreach ($products as $product): ?>
    <tr>
        <td><?php echo $product->getId(); ?></td>
        <td><?php echo $product->getName(); ?></td>
        <td><?php echo $product->getPrice(); ?></td>
        <td><?php echo $product->getDescription(); ?></td>
        <td><?php echo $product->getDate()->format("d/m/Y"); ?></td>
        <td>
            <a href="<?php echo $this->generateUrl('orm_edit', ['id' => $product->getId()]); ?>">Modifier</a> -
            <a href="<?php echo $this->generateUrl('orm_remove', ['id' => $product->getId()]); ?>">Supprimer</a>
        </td>
    </tr>
    <?php endforeach; ?>
</table>

[endblock]
